source 'http://rubygems.org'
gem 'haml'
gem 'sass'
gem 'compass'
gem 'compass-h5bp'
gem 'compass-placeholders'
gem 'middleman', '~> 3'
gem 'sinatra'
gem 'net-ssh'
gem 'net-sftp'
gem 'net-scp'
gem 'minisyntax'
gem 'middleman-sprockets'
gem 'middleman-blog'
gem 'rdiscount'

